version: '2'
services:
  buildfarm:
    build:
      context: alpine_maven
    volumes:
      - build:/maven_build/
    networks:
      - net
    restart: on-failure
  servlets:
    build:
      context: alpine_tomcat
    depends_on:
      - buildfarm
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - net
    restart: always
networks:
   net:
     driver: bridge
volumes:
  build: {}