version: '2'
volumes:
  build: {}
services:
  maven:
    build:
      context: alpine_maven
    volumes:
      - build:/maven_build/
    networks:
      - net

  tomcat:
    build:
      context: alpine_tomcat
    volumes_from:
      - maven
    ports:
      - "8080:8080"
    networks:
      - net
    links:
      - maven

networks:
   net:
     driver: bridge