version: '2'
services:
  maven:
    build:
      context: alpine_maven
    networks:
      - net
    restart: always
  tomcat:
    build:
      context: alpine_tomcat
    depends_on:
      - maven
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - net
    restart: always

networks:
   net:
     driver: bridge